### ISSUE TITLE
I want to help you with documentation and Korean.

### ISSUE THREAD

**Issue by yoonbincho** [Gamelab-Istanbul/NgdroidApp#32]
I am a software developer who is interested in this program. I want to help you with Hangulization and document work in this program.

**Comment by noyanc** [comment]
Hello yoonbincho, Thank you for interesting in the documentation and Korean of the Ngdroidapp. 

We prepare a website for Ngdroidapp. If you prepare the documentation, we can put it at the website with your name.

Did you do any game with Ngdroidapp? Do you know how to use it in the mobile game development?

**Comment by yoonbincho** [comment]
Thank you for taking a positive look. Korean document preparation can help you perfectly. Would you like to upload it as soon as you're ready?

**Comment by noyanc** [comment]
Done.
